Задача 12.1
PavelSaltykov/Course1 pull request #18
Opened 2019-12-21 00:12 UTC by PavelSaltykov

2019-12-21 00:17 UTC, PavelSaltykov commented on HW12/12.1/12.1/RabinKarp.cpp
> +const int q = INT_MAX;
Не работает с маленькими q

2019-12-21 00:20 UTC, PavelSaltykov commented on HW12/12.1/12.1/12.1.cpp
> +	return rabinKarp(string1, string2) == 1;
Не проходит тест с длинной подстрокой

2019-12-21 00:30 UTC, PavelSaltykov commented on HW12/12.1/12.1/RabinKarp.cpp
> +		const int tempHash = helpHash - string[i] * help % q;
tempHash может быть меньше нуля, если подстрока длинная

2019-12-21 13:16 UTC, yurii-litvinov requested changes

2019-12-21 13:16 UTC, yurii-litvinov commented on HW12/12.1/12.1/RabinKarp.cpp
> +	help /= x;
Вот это неправда. При арифметическом  переполнении `help *= x;` даст нам `help * x mod 2^32` (на самом деле даже `help * x mod 2^32 - 2^31`, раз речь идёт про знаковые целые, но сути дела это не меняет), а `(help * x mod 2^32) / x != help` --- мы делим на x остаток, а не произведение. Так что правильно тут `help = degreesOfX[substringLength - 1];`. Поэтому программистам надо знать теорию чисел.

2019-12-21 14:30 UTC, PavelSaltykov commented on HW12/12.1/12.1/RabinKarp.cpp
> +const int q = 991;
С маленьким q всё равно не работает :(

2019-12-21 20:08 UTC, yurii-litvinov commented
А теперь проблемы с всё той же алгеброй и знаками. Например, -351 mod 991 равно 640 mod 991 как элемент кольца вычетов Z/991, но оператор == про это ничего не знает. Надо "нормализовать" используемые значения (например, функцией λx.(x + 991) % 991).

2019-12-22 10:07 UTC, yurii-litvinov approved these changes
А я б делал все вычисления хеша с unsigned вместо int, чтобы о знаках не думать :) Хорошо, зачтена.

2019-12-22 10:33 UTC, merged