4.3
PavelSaltykov/Course1 pull request #5
Opened 2019-10-13 12:52 UTC by PavelSaltykov

2019-10-13 14:12 UTC, yurii-litvinov requested changes

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +#include <windows.h>
Нельзя, его под линуксом нету, а надо писать максимально кроссплатформенный код

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +		strncat(entries[amountOfEntriesInBuffer], phoneNumber, strlen(phoneNumber));
Мм, эта задача была на использование структур на самом деле :) Иначе операции типа поиска делать неудобно, да и если в имени пробел, то печаль.

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +			char buffer[entryLength]="";
Пробелов не хватает, да и инициализировать его лучше через `{}`, чтобы не смущать читателей

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +		fclose(file);
fclose не отработает, если отработает return phoneNumberInBuffer

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +		fclose(file);
И, кстати, а правда, что оно только по файлу ищет, а новые записи в буфере --- нет?

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +}
Возможно, было бы разумнее зачитать в начале работы программы все записи в буфер, работать с буфером, и файл трогать только при команде сохранения. Потому что доступ к файлам на диске в разы медленнее, чем к памяти.

2019-10-13 14:12 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +		memset(entries, 0, sizeof(entries));
А зачем? :)

2019-10-13 17:20 UTC, PavelSaltykov commented on HW4/4.3/4.3/4.3.cpp
> +#include <windows.h>
Тогда как вводить русские буквы?

2019-10-13 17:23 UTC, PavelSaltykov commented on HW4/4.3/4.3/4.3.cpp
> +}
Получается, при сохранении нужно перезаписать файл ("w")?

2019-10-13 19:22 UTC, yurii-litvinov commented on HW4/4.3/4.3/4.3.cpp
> +}
Ага

2019-10-15 16:59 UTC, yurii-litvinov approved these changes

2019-10-15 18:55 UTC, merged